language: node_js

os:
  - linux

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

dist: xenial
# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4
  chrome: stable

env:
  - HOST=localhost PORT=4550

services:
  - xvfb

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=4550 http://localhost &

branches:
  only:
  - gh-pages
  - /.*/

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info
install:
  - npm ci
defaults: &defaults
  script:
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm run start:ci &
    - npm run cy:run
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true