language: node_js
os:
- linux
node_js:
- 10.8
dist: xenial
addons:
  apt:
    packages:
    - libgconf-2-4
  chrome: stable
env:
  matrix:
  - HOST=localhost PORT=4550
  global:
    secure: PMYrvintWfVw7ORIuW4FHjzInXi4KBh2pxNhyl1r00kJ3hLt4CGIjOn9NOODBJ5eCR8F/FPOwB9PgoN6YPd7oDLgbvZkNFWqxJFvYBN3LdgiYMQDIRudvuOtFZYDggyKeas0E3X+HUMdIiVmhsDTGNV+zyygjSb4BG5LzB+P0Z+tzotuvQPL45AxzgtTVAlEtQ7/Ob2Iz7slGANHsVHVgecDW/GTG53/OZ9QVgS1SFrfvmH9XKlzDLz/TaFDbLOigjdyBybzujjrwdjiz0a0pvUom5nLS8eQf0OdtVOpqoGNlWPM/VeOs6OCSzBsgCIxopSwBov/wOGDNSqQIIO+WDgSSjqMMAlxuL2AyWGjBXDGzKMVsT28jrli375L6npkb/6FjaE6hyzeH7UFn7h89A1HGLEBQ1mVPtix8wAchmCbz7GWO2FEwiTkeqEdSuJx5Ir7VPj0AKhBf54nfDcb85LQpo2pXoJT3L3oo/QQDzS+mU+bW/pWijDP9Ou17bEDnR2PvMyCXeeid2tf/XtuZHfrhKRcSZv8UZSJNcuiPD7sNBVDKuh27BtUrm9tIW9qgUsb/vjvtvMaYS7kRgMbIV2aeLj4lktsaBaM2uKSyYMZjvC1WSP8drILWRJTGFsmymH1OWDMSPuOQbRKseHAfIbJCLyPHkiIR5xjIyr6aEw=
services:
- xvfb
before_install:
- google-chrome-stable --headless --disable-gpu
branches:
  only:
  - gh-pages
  - "/.*/"
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  override:
  - npm ci
  - npm run cy:verify
  - npm run cy:info
install:
- npm ci
defaults:
  script:
  - "$(npm bin)/print-env TRAVIS"
  - npm run start:ci &
  - npm run cy:run
  - kill $(jobs -p) || true
